//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalDC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public int InvoiceID { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public string Note { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
